# Eight queens puzzle - step by step explaination

## Eight queens puzzle
The eight queens puzzle is the problem of placing eight chess queens on an 8×8 chessboard so that no two queens threaten each other; thus, a solution requires that no two queens share the same row, column, or diagonal.

## Objective
Our objective is to generate the right sequence of Queen's positions using Genetic algorithm.  
One of the right sequence is **5 2 4 7 0 3 1 6**
* Each value represent the Queen's position on every column from 0-7 on the chess board.
* Each individual value ranges from 0-7, for every row on the chess board.

## Steps involved
1. Initial population is generated with chromosomes containing random genes.
2. Fitness score of the population is calculated.
3. Based on fitness score, parents are selected for mating.
4. Crossover and Mutation are performed on the selected parents, to produce offsprings.
5. Offsprings are added to the population and Fitness score is calculated.
6. Process is stopped if max-fitness score is found, else repeated from Step 3 to 5

## Setup functions

We are running "Eight queens puzzle.ipynb" file, to import the functions.

*Note: This step would execute all code on the mentioned file*

In [40]:
# import libraries
import numpy as np
import pandas as pd

In [41]:
# to hide outputs
%%capture 
# to run "Eight queens puzzle.ipynb" file
%run "./Eight queens puzzle.ipynb"

## Generate initial-population

Generating an initial-population of 100 chromosome(aka individuals) with random genes.

In [50]:
# Generate initial-population
init_pop = generate_init_pop(initial_population_size)

# display top 5 initial-population
init_pop[:5]

[array([1, 5, 2, 0, 2, 6, 2, 7]),
 array([3, 1, 1, 6, 0, 6, 5, 3]),
 array([2, 6, 2, 7, 3, 3, 0, 1]),
 array([3, 4, 5, 1, 0, 0, 0, 0]),
 array([3, 1, 6, 2, 2, 4, 3, 7])]

Inspecting the first chromosome below, we can see it's an array of sequence randomly generated, having values from 0-7 indicating the position of the Queens across the board.  

*Note: Each individual array elements are called Genes*

In [51]:
# First chromosome
init_pop[0]

array([1, 5, 2, 0, 2, 6, 2, 7])

## Calculating fitness score
Fitness score is calculated for every chromosome in the population, to indentify how close are the sequence to the right sequence.  
The fitness score function defined would do the following:
* Starting from the queen at 0th column, checks how many queens are in attacking position to the queen in 0th position
* For every successful non-attacking position 1 point is added
    * So if none of the queens are attacking the 0th queen, thes the score is 7
    * If all the queens are in attacking position to 0th queen, then the score is 0
* This step is repeated for the rest of the columns

**The right sequence would score 56**

We'll try calculating the fitness score of the first chromosome

In [52]:
chromosome1_fitness = fitness_score(init_pop[0])
print(f"First chromosome's fitness score is {chromosome1_fitness}")

First chromosome's fitness score is 44


## Probability of fitness score
We'd then calculate the probabiltiy of the fitness score, to choose parents with high probability to produce offsprings.

**The best fitness score 56, would have a probability of 1.0**

In [53]:
chromosome1_probability = get_probability([chromosome1_fitness], target_value = 56)
print(f"First chromosome's probability is {chromosome1_probability[0]}")

First chromosome's probability is 0.78571


In similar fashion we'll calculate the fitness score and probability of the initial population, to choose the parents.

In [54]:
init_pop_score = get_dataframe(init_pop)
# Top five chromosomes with high probability
init_pop_score.head(5)

combination  fitness  probability
0  [6, 4, 0, 5, 6, 2, 3, 7]       50      0.89286
1  [4, 2, 7, 6, 2, 5, 2, 0]       48      0.85714
2  [3, 6, 0, 1, 5, 7, 3, 6]       48      0.85714
3  [4, 6, 6, 2, 0, 7, 3, 5]       48      0.85714
4  [3, 1, 6, 2, 2, 4, 3, 7]       46      0.82143

## Selecting children
Parents are chosen on the order of high probability and they undergo [crossover](https://www.tutorialspoint.com/genetic_algorithms/genetic_algorithms_crossover.htm) and [mutation](https://www.tutorialspoint.com/genetic_algorithms/genetic_algorithms_mutation.htm) to produce offsprings.

### Crossover
We perform One Point crossover between two parents to produce two offsprings, who will get traits from both parents.

Example:

Parent 1: 0 0 0 0 0 0 0 0  
Parent 2: 8 8 8 8 8 8 8 8  

We select a crossover point in the middle and the tails of the two parents are swapped to get new offsprings.

Child 1: 0 0 0 0 8 8 8 8  
Child 2: 8 8 8 8 0 0 0 0 

In [55]:
# Parents
parent1 = np.full(8, 0)
parent2 = np.full(8, 8)

# Children
child1, child2 = crossover(parent1, parent2, crossOver=0.5)

print(f"Parent 1 : {parent1} \nParent 2 : {parent2}")
print(f"Child 1 : {child1} \nChild 2 : {child2}")

Parent 1 : [0 0 0 0 0 0 0 0] 
Parent 2 : [8 8 8 8 8 8 8 8]
Child 1 : [0 0 0 0 8 8 8 8] 
Child 2 : [8 8 8 8 0 0 0 0]


### Mutation
We apply Random Resetting mutation on the obtained offsprings.

In this method we simply choose a gene randomly and replace it with a random value from the set of permissible values (0 - 7)


In [48]:
# Applying mutation on the obtained offsprings
child1 = mutation(child1); child2 = mutation(child2)

print(f"Child 1 : {child1} \nChild 2 : {child2}")

Child 1 : [0 0 0 0 8 8 8 8] 
Child 2 : [1 8 8 8 0 0 0 0]


We then proceed to score the fitness of the obtained offsprings and the we add them to the initial population.

Then we try to find, if we have got the right sequence (based on the fitness score). If not then we repeat the whole process again to generate new offsprings until we have the expected fitness.

In [56]:
# store right sequence
right_sequence = generate_sequence(init_pop, num_of_children, num_of_generation, target_value)

expected fitness: 56 
----------------------------------n
Gen: 0 , best-combination: [6 4 0 5 6 2 3 7] , fitness: 50 , avg-fitness: 42.5 , probability: 0.89286
Gen: 1 , best-combination: [5 0 4 1 6 2 3 7] , fitness: 52 , avg-fitness: 42.707 , probability: 0.92857
Gen: 2 , best-combination: [5 0 4 1 6 2 3 7] , fitness: 52 , avg-fitness: 42.94 , probability: 0.92857
Gen: 3 , best-combination: [5 0 4 1 6 2 3 7] , fitness: 52 , avg-fitness: 43.016 , probability: 0.92857
Gen: 4 , best-combination: [5 0 4 1 6 2 3 7] , fitness: 52 , avg-fitness: 43.273 , probability: 0.92857
Gen: 5 , best-combination: [1 5 2 0 6 3 1 4] , fitness: 52 , avg-fitness: 43.497 , probability: 0.92857
Gen: 6 , best-combination: [1 5 2 0 6 3 1 4] , fitness: 52 , avg-fitness: 43.56 , probability: 0.92857
Gen: 7 , best-combination: [5 3 6 0 2 4 7 3] , fitness: 54 , avg-fitness: 43.578 , probability: 0.96429
Gen: 8 , best-combination: [5 3 6 0 2 4 7 3] , fitness: 54 , avg-fitness: 43.8 , probability: 0.96429
Gen: 9 , bes

In [57]:
# Display the right sequence
right_sequence_str = " ".join([str(i) for i in right_sequence.tolist()])
print("Sequence :", right_sequence_str)

Sequence : 5 1 6 0 3 7 4 2
